### ISSUE TITLE
Allow multiple device pairing with Telegram

### ISSUE THREAD

**Issue by milvi** [igrmk/smsq#10]
I have 2 phones. I installed Telegram and smsq on each device. On both I use the same personal Telegram account. However, when pairing on a device, it nullifies/disables the pairing on the other one. At any time, only one device forwards messages.

I suspect there is a unique token for authentication so it can't use two duplicate instances for now (wild guess !) 

Would you be able to lift that limitation ?

**Comment by igrmk** [comment]
Hello guys! I've just deprecated this project. Please feel free to fork it
