### ISSUE TITLE
Not working with Telegram Version 9.7.6

### ISSUE THREAD

**Issue by devmalick** [igrmk/smsq#16]
Smsq not working with Telegram Version 9.7.6. Please do the needful

**Comment by tarasverq** [comment]
@devmalick Author's backend doesn't seem to work anymore.

Check out [ my fork](https://github.com/tarasverq/smsq) It allows you to set up your own backend or use the public one.

**Comment by crozo5** [comment]
Same here

**Comment by devmalick** [comment]
Smsq not working with FOSS Telegram Version 10.0.9. Please do the needful. : showing error "username not found"

**Comment by igrmk** [comment]
Hello guys! I've just deprecated this project. Please feel free to fork it
