### ISSUE TITLE
Does it need to use a server?

### ISSUE THREAD

**Issue by jesshampshire** [igrmk/smsq#4]
Could the app simply use a private channel instead?

**Comment by igrmk** [comment]
Probably you can create a private channel programmatically via TDLib but I cannot imagine such a simple user experience that is possible using the Bot API. Currently you just press "CONNECT TELEGRAM" in the app and then "START" inside Telegram. I really want to keep it that simple. If you know such a way please share. And PRs are even more welcome. Thank you!

**Comment by NOBLES5E** [comment]
> Probably you can create a private channel programmatically via TDLib but I cannot imagine such a simple user experience that is possible using the Bot API. Currently you just press "CONNECT TELEGRAM" in the app and then "START" inside Telegram. I really want to keep it that simple. If you know such a way please share. And PRs are even more welcome. Thank you!

Current implementation implies all user's SMS will go through your server in clear text. Am I misunderstanding anything?

**Comment by igrmk** [comment]
SMS payload comes to the server encrypted by the app (hybrid encryption by Google Tink) and also TLS or SSL (if your phone is old enough). Then it is decrypted to a clear text. And then it goes to Telegram servers encrypted by TLS. If your question was should you trust me if you use this service, then the answer is yes, this is how it works at the moment.

**Comment by jesshampshire** [comment]
The way I would imagine it would work would be it would use parts of original Telegram code. It would use the normal Telegram login at the start, then ask if all text messages were to come in one channel or a channel for each sender.

Then it would either create a channel Messages to +<phone number> for all messages or Message from Name (if known number if not) with details in the channel description. 

Then it would copy each text message to the relevant channel.

Though obviously I can see making a bot would provide much more useful experience, of course, but it seems to add a redundant step.
