### ISSUE TITLE
Allow using user's own Telegram bot

### ISSUE THREAD

**Issue by abacabadabacaba** [igrmk/smsq#9]
I don't want my messages to pass through your server. I would rather register my own Telegram bot, so that the app would use Telegram API directly to send messages as that bot. Could this be done?

**Comment by tarasverq** [comment]
@abacabadabacaba @Kolsha @not-poma
Check out [my fork](https://github.com/tarasverq/smsq) It allows you to set up your own backend or use the public one.

**Comment by igrmk** [comment]
Hello guys! I've just deprecated this project. Please feel free to fork it
